# Generated by Django 5.1.4 on 2024-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('Cloud Service Provider', 'Cloud Service Provider'), ('Software Vendor', 'Software Vendor'), ('Network Infrastructure', 'Network Infrastructure'), ('Data Center', 'Data Center'), ('Other', 'Other')], max_length=50)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='industry',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('Cloud Service Provider', 'Cloud Service Provider'), ('Software Vendor', 'Software Vendor'), ('Network Infrastructure', 'Network Infrastructure'), ('Data Center', 'Data Center'), ('Other', 'Other')], default='Cloud Service Provider', max_length=50),
        ),
        migrations.DeleteModel(
            name='SecurityChecklist',
        ),
    ]
