# Generated by Django 5.1.4 on 2025-02-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='category',
            field=models.CharField(choices=[('Security', 'Security'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Operational', 'Operational')], default='Security', max_length=50),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='insurance_coverage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='years_in_operation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorresponse',
            name='response',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial'), ('N/A', 'N/A')], max_length=255),
        ),
        migrations.CreateModel(
            name='OnboardingQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_questions', to='vendor_risk.vendor')),
            ],
        ),
    ]
