# Generated by Django 5.1.4 on 2025-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('Cloud Service Provider', 'Cloud Service Provider'), ('Software Vendor', 'Software Vendor'), ('Network Infrastructure', 'Network Infrastructure'), ('Data Center', 'Data Center'), ('Other', 'Other')], max_length=50)),
                ('requires_certification', models.BooleanField(default=False)),
                ('min_employees', models.PositiveIntegerField(default=0)),
                ('max_employees', models.PositiveIntegerField(default=10000)),
                ('category', models.CharField(choices=[('General', 'General'), ('Technical', 'Technical'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Operational', 'Operational')], max_length=50)),
            ],
        ),
    ]
