# Generated by Django 5.1.4 on 2025-01-07 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0002_questionnaire_remove_vendor_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vendor_risk.questionnaire')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vendor_risk.vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DashboardMetric',
        ),
        migrations.DeleteModel(
            name='RiskCategory',
        ),
        migrations.RemoveField(
            model_name='standardscompliance',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendordocument',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Non-Compliant', 'Non-Compliant')], default='Non-Compliant', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='StandardsCompliance',
        ),
        migrations.DeleteModel(
            name='VendorDocument',
        ),
    ]
