# Generated by Django 5.1.4 on 2025-03-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0002_questionnairerules'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General', 'General'), ('Technical', 'Technical'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Operational', 'Operational')], default='General', max_length=50)),
                ('question_text', models.TextField()),
                ('requires_mfa', models.BooleanField(default=False)),
                ('cloud_requirement', models.CharField(blank=True, choices=[('Public Cloud', 'Public Cloud'), ('Private Cloud', 'Private Cloud'), ('Hybrid Cloud', 'Hybrid Cloud'), ('No Cloud', 'No Cloud')], max_length=50, null=True)),
                ('min_employees', models.PositiveIntegerField(default=0)),
                ('max_employees', models.PositiveIntegerField(default=10000)),
                ('required_certifications', models.ManyToManyField(blank=True, to='vendor_risk.certification')),
                ('vendor_types', models.ManyToManyField(blank=True, to='vendor_risk.vendor')),
            ],
        ),
    ]
