# Generated by Django 5.1.4 on 2025-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0002_questionnaire_category_questionnaire_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
