# Generated by Django 5.1.4 on 2025-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0003_customuser_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='certifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
