# Generated by Django 5.1.4 on 2025-03-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0003_questionbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='vendor_types',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='vendor_type',
            field=models.CharField(choices=[('Cloud Service Provider', 'Cloud Service Provider'), ('Software Vendor', 'Software Vendor'), ('Network Infrastructure', 'Network Infrastructure'), ('Data Center', 'Data Center'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vendor_risk.questionbank'),
        ),
    ]
