# Generated by Django 5.1.4 on 2025-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0004_remove_customuser_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
