# Generated by Django 5.1.4 on 2025-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0004_remove_questionbank_vendor_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('Cloud Service Provider', 'Cloud Service Provider'), ('Software Vendor', 'Software Vendor'), ('Network Infrastructure', 'Network Infrastructure'), ('Data Center', 'Data Center'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
