# Generated by Django 5.1.4 on 2025-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0005_alter_questionbank_vendor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='securitychecklist',
            name='category',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='total_risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securitychecklist',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
