# Generated by Django 5.1.4 on 2025-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0006_remove_riskassessment_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Technical', 'Technical'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Operational', 'Operational')], max_length=50)),
                ('is_critical', models.BooleanField(default=False)),
                ('vendor_type', models.CharField(choices=[('Cloud Service Provider', 'Cloud Service Provider'), ('Software Vendor', 'Software Vendor'), ('Network Infrastructure', 'Network Infrastructure'), ('Data Center', 'Data Center'), ('Other', 'Other'), ('Any', 'Any')], default='Any', max_length=50)),
                ('standard_required', models.BooleanField(default=False)),
                ('compliance_standard', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
