# Generated by Django 5.1.4 on 2025-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0007_vendor_submitted_at_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
