# Generated by Django 5.1.4 on 2025-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0007_securitychecklisttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitychecklist',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Technical', 'Technical'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Operational', 'Operational')], max_length=50, null=True),
        ),
    ]
