# Generated by Django 5.1.4 on 2025-03-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0008_alter_vendor_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendorresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vendorresponse',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption', models.BooleanField(default=False)),
                ('mfa', models.BooleanField(default=False)),
                ('rbac', models.BooleanField(default=False)),
                ('penetration_testing', models.BooleanField(default=False)),
                ('cloud_usage', models.CharField(choices=[('Public Cloud', 'Public Cloud'), ('Private Cloud', 'Private Cloud'), ('Hybrid Cloud', 'Hybrid Cloud'), ('No Cloud', 'No Cloud')], default='No Cloud', max_length=50)),
                ('certifications', models.ManyToManyField(blank=True, to='vendor_risk.certification')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to='vendor_risk.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='OnboardingQuestionnaire',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='VendorResponse',
        ),
    ]
