# Generated by Django 5.1.4 on 2025-03-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0010_remove_vendor_num_employees_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Technical', 'Technical'), ('Compliance', 'Compliance'), ('Legal', 'Legal'), ('Operational', 'Operational')], default='General', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial'), ('N/A', 'N/A')], max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vendor_risk.onboardingquestionnaire')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='vendor_risk.vendor')),
            ],
        ),
    ]
