# Generated by Django 5.1.4 on 2025-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0011_onboardingquestionnaire_vendorresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='certifications',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='certified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='vendor_risk.certification'),
        ),
    ]
