# Generated by Django 5.1.4 on 2025-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_risk', '0012_remove_vendor_certifications_alter_vendor_certified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='vendor_risk.certification'),
        ),
    ]
