version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: riskavanta
      DB_USER: postgres
      DB_PASSWORD: sorryla
      DB_HOST: host.docker.internal
      DB_PORT: 5432
