version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sorryla
      POSTGRES_DB: riskavant
    ports:
      - "5432:5432"
    
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
